restart_file: .na
start_day_local: '2018-10-10'
start_time_local: '07:00:00'
end_day_local: .na
forecast_start_day_local: '2018-10-11'
forecast_horizon: 16.0
forecast_project_id: test
sim_name: test
forecast_sss_on: yes
forecast_location: /Users/quinn/Dropbox/Research/SSC_forecasting/FLARE_package/flare_lake_examples/fcre/glm/
execute_location: /Users/quinn/Dropbox/Research/SSC_forecasting/FLARE_package/flare_lake_examples/fcre/glm/
